general.import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font Mono", style = "italic"}
size = 14.0

[window]
decorations = "Buttonless"
opacity = 0.80
blur = true
padding = { x = 3, y = 3 }
option_as_alt = "OnlyLeft"

